// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const changeChirpRedStatus = `-- name: ChangeChirpRedStatus :one
UPDATE users SET is_chirpy_red = TRUE, updated_at = NOW() where id = $1 RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

func (q *Queries) ChangeChirpRedStatus(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, changeChirpRedStatus, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const changeUserCreds = `-- name: ChangeUserCreds :one
UPDATE users SET email = $1, hashed_password = $2, updated_at = NOW() where id = $3 RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type ChangeUserCredsParams struct {
	Email          string
	HashedPassword string
	ID             uuid.UUID
}

func (q *Queries) ChangeUserCreds(ctx context.Context, arg ChangeUserCredsParams) (User, error) {
	row := q.db.QueryRowContext(ctx, changeUserCreds, arg.Email, arg.HashedPassword, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(
    id, created_at, updated_at, email,hashed_password
) VALUES(
    $1,$2,$3,$4,$5
)
RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type CreateUserParams struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Email,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUsers)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, email, hashed_password, is_chirpy_red FROM users where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}
